version: '3.8'

services:

  news_api:
    container_name: news_api
    build: ./news_api
    ports:
      - "5001:5000"
    volumes:
      - ./news_api:/app
    networks:
      - news-network
    env_file:
      - .env

  data_transfer:
    build:
      context: ./data_transfer
      dockerfile: Dockerfile-worker
    env_file:
      - .env
    networks:
      - news-network

  data_transfer_beat:
    build:
      context: ./data_transfer
      dockerfile: Dockerfile-beat
    env_file:
      - .env
    networks:
      - news-network

  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - news-network
    restart: on-failure

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - news-network

networks:
  news-network:
    name: news-network
    driver: bridge

volumes:
  mongodbdata:
    name: mongodbdata
