version: '3.8'

services:

#  news_api:
#    container_name: news_api
#    build: ./news_api
#    volumes:
#      - ./news_api:/app
#    networks:
#      - news-network

  scarpers:
    build:
      context: ./scarpers
    networks:
      - news-network

  rabbit:
    image: rabbitmq:latest
    logging:
      driver: none
    ports:
      - "5672:5672"
    networks:
      - news-network
    restart: on-failure

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  news-network:
    name: news-network
    driver: bridge

volumes:
  postgresdata:
    name: postgresdata
